// images.js
export default {
  "balon_futbol.webp": require("../../assets/images/balon_futbol.webp"),
  "bicicleta_nino.webp": require("../../assets/images/bicicleta_nino.webp"),
  "caja_herramientas.webp": require("../../assets/images/caja_herramientas.webp"),
  "control_xbox.webp": require("../../assets/images/control_xbox.webp"),
  "flauta.webp": require("../../assets/images/flauta.webp"),
  "game_boy.webp": require("../../assets/images/game_boy.webp"),
  "guitarra.webp": require("../../assets/images/guitarra.webp"),
  "libro_charles_dickens.webp": require("../../assets/images/libro_charles_dickens.webp"),
  "libro_edgar_allan_poe.webp": require("../../assets/images/libro_edgar_allan_poe.webp"),
  "libro_gabo.webp": require("../../assets/images/libro_gabo.webp"),
  "libro_jj_benitez.webp": require("../../assets/images/libro_jj_benitez.webp"),
  "libro_miguel_de_cervantes.webp": require("../../assets/images/libro_miguel_de_cervantes.webp"),
  "libro_nietzsche.webp": require("../../assets/images/libro_nietzsche.webp"),
  "libro_paulo_cohelo.webp": require("../../assets/images/libro_paulo_cohelo.webp"),
  "licuadora.webp": require("../../assets/images/licuadora.webp"),
  "linterna.webp": require("../../assets/images/linterna.webp"),
  "monopatin_nino.webp": require("../../assets/images/monopatin_nino.webp"),
  "monopoly.webp": require("../../assets/images/monopoly.webp"),
  "mueble.webp": require("../../assets/images/mueble.webp"),
  "multitoma.webp": require("../../assets/images/multitoma.webp"),
  "sofa_descanso.webp": require("../../assets/images/sofa_descanso.webp"),
  "silla_mesedora.webp": require("../../assets/images/silla_mesedora.webp"),
  "tambor.webp": require("../../assets/images/tambor.webp"),
};
